spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  http:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  redis:
    database: 0    #数据库索引
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200   #最大连接数
        max-wait: -1      #最大阻塞时间
        max-idle: 10      #最大空闲连接数
        min-idle: 0       #最小空闲连接
    timeout: 5000         #连接超时
  rabbitmq:
    host: 127.0.0.1
    port: 5672

mybatis:
  mapper-locations: classpath:mapper/**.xml, classpath:extMapper/**.xml

logging:
  level:
    ucar.train.security.mapper: debug
    ucar.train.security.module.room.mapper: debug



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8092
  servlet:
    context-path: /bbs_server

wx:
  login:
    appId: wxb637a36cf6f08039
    appSecret: 8f1dc58fa9b297b539e8ff4a905a247e
    interfaceUrl: https://api.weixin.qq.com
  message:
    check_result_template_id: EXRvqLjpGw5kyT8WNOnY_nfQ38wlLXnmG63rv_6ESDQ


disable:
  score: 80
